#!/bin/bash
# -----------------------------------------------------------------------------
# docker-minecraft /start script
#
# Authors: Isaac Bythewood
# Updated: Dec 14th, 2014
# -----------------------------------------------------------------------------

if [ $# -ne 1 ]; then
  echo "Invalid parameter. Please specify the version." 1>&2
  exit 1
fi

use_version=$1

active_version=`cat /data/version.txt`

if [ ! -f /data/minecraft_server.jar -o "$use_version" != "$active_version" ]; then
    url="https://s3.amazonaws.com/Minecraft.Download/versions/${use_version}/minecraft_server.${use_version}.jar"
    curl $url -o /data/minecraft_server.jar
    echo $use_version > /data/version.txt
fi

if [ ! -f /data/eula.txt ]
then
    echo "eula=true" > /data/eula.txt
fi

cd /data/; java -Xmx2G -jar minecraft_server.jar nogui

